### PR TITLE
Add TZKT functions

### PR DESCRIPTION
**Pull request by minhkstn**
Related story: [Make a tzkt api a standalone library#1881](https://github.com/bitmark-inc/autonomy/issues/1881)

### CODE REVIEW

**Review by lemonlatte — CHANGES_REQUESTED** [review]
- refactor this by using `func (c *TZKT) request(req *http.Request, responseData interface{}) error`
- can `TransactionDetails` and `Transaction` be merged?
- by first look, please group functions by apis into the following files
  - operation.go
  - token.go
  - bigmap.go

**Comment by minhkstn** [comment]
> refactor this by using func (c *TZKT) request(req *http.Request, responseData interface{}) error

@lemonlatte Sorry I don't get your point. Can you clarify?

**Comment by lemonlatte** [comment]
> > refactor this by using func (c *TZKT) request(req *http.Request, responseData interface{}) error
> 
> @lemonlatte Sorry I don't get your point. Can you clarify?

there is a requests function in the code, we should use it for all request instead of make http calls directly using http library.

**Comment by minhkstn** [comment]
@lemonlatte I got it. I updated the code. Please help me check it. Thanks.

**Review by lemonlatte — APPROVED** [review]
So far so good. Let's tweak further during the integration

**Pull request merged**
